btnAnswer.addEventListener("click", async () => {
    let [tab] = await chrome.tabs.query({ active: true, currentWindow: true });

    chrome.scripting.executeScript({
        target: { tabId: tab.id },
        function: answerFields,
    });
});

const answerFields = () => {
    var data = {
        "A": {
            "CARRO": ["AUDI"],
            "ALIMENTO": ["ARROZ", "ALFACE", "ALHO"],
            "IDIOMA": [""],
            "DOCE": [""],
            "PDA": ["AGATHA HARKNESS"],
            "CEP": ["AVARE"],
            "MSE": ["AMAVEL"],
            "CELEBRIDADE": ["AMY WHINEHOUSE"],
            "ELETRO ELETRONICO": [""],
            "VERBO": [""],
            "APP OU SITE": [""],
            "ESPORTE": ["ARCO E FLECHA"],
            "VESTUARIO": [""],
            "JLR": [""],
            "SERIE": ["ANNE COM E"],
            "FILME": ["ABRACADABRA"],
            "INSETO": [""],
            "MUSICA": [""],
            "LIQUIDO": [""],
            "PCH": ["AMIDALA"],
            "NOME MASCULINO": ["ANDRE"],
            "NOME FEMININO": ["AMANDA"],
            "ADJETIVO": ["AMIGAVEL"],
            "BANDA": ["AEROSMITH"],
            "PROFISSAO": ["ANALISTA"],
            "INSTRUMENTO MUSICAL": ["ATABAQUE"],
            "FLV": [""],
            "GENTILICO": [""],
            "CIDADE": [""],
            "GAME": ["ASSASSINS CREED"],
            "PERSONAGEM FICTICIO": ["ARIEL"],
            "ATOR": ["ANGELINA JOLIE"],
            "TIME ESPORTIVO": ["ARSENAL"],
            "OBJETO": ["AGULHA"],
            "SUPER-HEROI": [""],
            "DESENHO ANIMADO": [""],
            "PALAVRA EM INGLES": [""],
            "SOBREMESA": [""],
            "CANTOR": [""],
            "CANTORA": [""],
            "REMEDIO": [""],
            "COR": ["AMARELO"],
            "FRUTA": ["ABACAXI", "ABACATE"],
            "ESPORTISTA": [""],
            "PAIS": ["ARGELIA"],
            "SOBRENOME": ["ALCANTARA"],
            "NOME": [""],
            "CAPITAL": [""],
            "MEIO DE TRANSPORTE": ["AVIAO"],
            "FLOR": ["ACASIA"],
            "MARCA": ["ANTARTICA"],
            "COMIDA": [""],
            "ANIMAL": ["ANDORINHA"],
            "PROGRAMA DE TV": [""]
        },
        "B": {
            "CARRO": ["BELINA"],
            "ALIMENTO": ["BOLO", "BOLACHA"],
            "IDIOMA": [""],
            "DOCE": [""],
            "PDA": ["BART SIMPSON"],
            "CEP": ["BRAGANCA PAULISTA"],
            "MSE": ["BELISSIMA"],
            "CELEBRIDADE": ["BOB MARLEY"],
            "ELETRO ELETRONICO": [""],
            "VERBO": [""],
            "APP OU SITE": [""],
            "ESPORTE": ["BOCHA"],
            "VESTUARIO": [""],
            "JLR": [""],
            "SERIE": ["BAND OF BROTHERS"],
            "FILME": ["BAD BOYS"],
            "INSETO": [""],
            "MUSICA": [""],
            "LIQUIDO": [""],
            "PCH": ["BUNDA"],
            "NOME MASCULINO": ["BRUCE"],
            "NOME FEMININO": ["BIANCA"],
            "ADJETIVO": ["BONDOSO"],
            "BANDA": ["BARAO VERMELHO"],
            "PROFISSAO": ["BANQUEIRO"],
            "INSTRUMENTO MUSICAL": ["BATERIA"],
            "FLV": [""],
            "GENTILICO": [""],
            "CIDADE": [""],
            "GAME": ["BORDERLANDS 3"],
            "PERSONAGEM FICTICIO": ["BRUCE BANNER"],
            "ATOR": ["BRUCE WILLIS"],
            "TIME ESPORTIVO": ["BARCELONA"],
            "OBJETO": ["BOLA AZUL"],
            "SUPER-HEROI": [""],
            "DESENHO ANIMADO": [""],
            "PALAVRA EM INGLES": [""],
            "SOBREMESA": [""],
            "CANTOR": [""],
            "CANTORA": [""],
            "REMEDIO": [""],
            "COR": ["BEGE"],
            "FRUTA": ["BANANA"],
            "ESPORTISTA": [""],
            "PAIS": ["BOLIVIA"],
            "SOBRENOME": ["BRANDAO"],
            "NOME": [""],
            "CAPITAL": [""],
            "MEIO DE TRANSPORTE": ["BARCO"],
            "FLOR": ["BROMELIA"],
            "MARCA": ["BIC"],
            "COMIDA": [""],
            "ANIMAL": ["BÓDE"],
            "PROGRAMA DE TV": [""]
        },
        "C": {
            "CARRO": ["CHEVETTE"],
            "ALIMENTO": ["CHOCOLATE", "CENOURA"],
            "IDIOMA": [""],
            "DOCE": [""],
            "PDA": ["CHICO BENTO"],
            "CEP": ["COLORADO"],
            "MSE": ["CHATA"],
            "CELEBRIDADE": ["CLAUDIA RAIA"],
            "ELETRO ELETRONICO": [""],
            "VERBO": [""],
            "APP OU SITE": [""],
            "ESPORTE": ["CORRIDA"],
            "VESTUARIO": [""],
            "JLR": [""],
            "SERIE": ["CALIFORNATICATION"],
            "FILME": ["CONSTANTINE"],
            "INSETO": [""],
            "MUSICA": [""],
            "LIQUIDO": [""],
            "PCH": ["CLAVICULA"],
            "NOME MASCULINO": ["CARLOS"],
            "NOME FEMININO": ["CAMILA"],
            "ADJETIVO": ["CALMO"],
            "BANDA": ["CAPITAL INICIAL"],
            "PROFISSAO": ["CONTADOR"],
            "INSTRUMENTO MUSICAL": ["CUICA"],
            "FLV": [""],
            "GENTILICO": [""],
            "CIDADE": [""],
            "GAME": ["CALL OF DUTY"],
            "PERSONAGEM FICTICIO": ["CURUPIRA"],
            "ATOR": ["CHRIS EVANS"],
            "TIME ESPORTIVO": ["CRUZEIRO"],
            "OBJETO": ["CANUDO"],
            "SUPER-HEROI": [""],
            "DESENHO ANIMADO": [""],
            "PALAVRA EM INGLES": [""],
            "SOBREMESA": [""],
            "CANTOR": [""],
            "CANTORA": [""],
            "REMEDIO": [""],
            "COR": ["CINZA"],
            "FRUTA": ["CEREJA"],
            "ESPORTISTA": [""],
            "PAIS": ["CAMAROES"],
            "SOBRENOME": ["CAMPOS"],
            "NOME": [""],
            "CAPITAL": [""],
            "MEIO DE TRANSPORTE": ["CARRO"],
            "FLOR": ["CALENDULA"],
            "MARCA": ["COLGATE"],
            "COMIDA": [""],
            "ANIMAL": ["CAMELO"],
            "PROGRAMA DE TV": [""]
        },
        "D": {
            "CARRO": ["DEL REY"],
            "ALIMENTO": ["DENDE", "DADINHO DE LEITE"],
            "IDIOMA": [""],
            "DOCE": [""],
            "PDA": ["DICK VIGARISTA"],
            "CEP": ["DINAMARCA"],
            "MSE": ["DRAMATICA"],
            "CELEBRIDADE": ["DADO DOLABELA"],
            "ELETRO ELETRONICO": [""],
            "VERBO": [""],
            "APP OU SITE": [""],
            "ESPORTE": ["DECATLO"],
            "VESTUARIO": [""],
            "JLR": [""],
            "SERIE": ["DEMOLIDOR"],
            "FILME": ["DRACULA"],
            "INSETO": [""],
            "MUSICA": [""],
            "LIQUIDO": [""],
            "PCH": ["DEDOS"],
            "NOME MASCULINO": ["DOUGLAS"],
            "NOME FEMININO": ["DAIANE"],
            "ADJETIVO": ["DEDICADO"],
            "BANDA": ["DETONALTAS"],
            "PROFISSAO": ["DIAGRAMADOR"],
            "INSTRUMENTO MUSICAL": ["DIAPASAO"],
            "FLV": [""],
            "GENTILICO": [""],
            "CIDADE": [""],
            "GAME": ["DEAD BY DAYLIGHT"],
            "PERSONAGEM FICTICIO": ["DEMOLIDOR"],
            "ATOR": ["DANIEL RADCLIFFE"],
            "TIME ESPORTIVO": ["DINAMO"],
            "OBJETO": ["DEDAL"],
            "SUPER-HEROI": [""],
            "DESENHO ANIMADO": [""],
            "PALAVRA EM INGLES": [""],
            "SOBREMESA": [""],
            "CANTOR": [""],
            "CANTORA": [""],
            "REMEDIO": [""],
            "COR": ["DOURADO"],
            "FRUTA": ["DAMASCO"],
            "ESPORTISTA": [""],
            "PAIS": ["DINAMARCA"],
            "SOBRENOME": ["DOMINGUES"],
            "NOME": [""],
            "CAPITAL": [""],
            "MEIO DE TRANSPORTE": ["DROMEDRARIO"],
            "FLOR": ["DALIA"],
            "MARCA": ["DISNEY"],
            "COMIDA": [""],
            "ANIMAL": ["DROMEDARIO"],
            "PROGRAMA DE TV": [""]
        },
        "E": {
            "CARRO": ["ECO SPORT"],
            "ALIMENTO": ["EMPADA", "ESPAGUETE"],
            "IDIOMA": [""],
            "DOCE": [""],
            "PDA": ["EUFRAZINO"],
            "CEP": ["ESPIRITO SANTO"],
            "MSE": ["ESTRANHA"],
            "CELEBRIDADE": ["ELIS REGINA"],
            "ELETRO ELETRONICO": [""],
            "VERBO": [""],
            "APP OU SITE": [""],
            "ESPORTE": ["ESGRIMA"],
            "VESTUARIO": [""],
            "JLR": [""],
            "SERIE": ["EL CHAVE DEL 8"],
            "FILME": ["ENROLADOS"],
            "INSETO": [""],
            "MUSICA": [""],
            "LIQUIDO": [""],
            "PCH": ["ESTOMAGO"],
            "NOME MASCULINO": ["EMILIO"],
            "NOME FEMININO": ["EMILIA"],
            "ADJETIVO": ["EFICIENTE"],
            "BANDA": ["ENGENHEIROS DO HAWAII"],
            "PROFISSAO": ["ENGENHEIRO"],
            "INSTRUMENTO MUSICAL": ["ESCALETA"],
            "FLV": [""],
            "GENTILICO": [""],
            "CIDADE": [""],
            "GAME": ["ENTER THE GUNGEON"],
            "PERSONAGEM FICTICIO": ["ELEVEN"],
            "ATOR": ["EMMA WATSON"],
            "TIME ESPORTIVO": ["ESTUDIANTE"],
            "OBJETO": ["ESPELHO"],
            "SUPER-HEROI": [""],
            "DESENHO ANIMADO": [""],
            "PALAVRA EM INGLES": [""],
            "SOBREMESA": [""],
            "CANTOR": [""],
            "CANTORA": [""],
            "REMEDIO": [""],
            "COR": ["ESCARLATE"],
            "FRUTA": ["EMBAÚBA"],
            "ESPORTISTA": [""],
            "PAIS": ["ESTONIA"],
            "SOBRENOME": ["ESPINOZA"],
            "NOME": [""],
            "CAPITAL": [""],
            "MEIO DE TRANSPORTE": ["EMPILHADEIRA"],
            "FLOR": ["ESPIRRADEIRA"],
            "MARCA": ["ELECTROLUX"],
            "COMIDA": [""],
            "ANIMAL": ["ESCORPIAO"],
            "PROGRAMA DE TV": [""] 
        },
        "F": {
            "CARRO": ["FERRARI"],
            "ALIMENTO": ["FEIJAO", "FAROFA"],
            "IDIOMA": [""],
            "DOCE": [""],
            "PDA": ["FRANGOLINO"],
            "CEP": ["FERNANDO DE NORONHA"],
            "MSE": ["FEIA"],
            "CELEBRIDADE": ["FERGIE"],
            "ELETRO ELETRONICO": [""],
            "VERBO": [""],
            "APP OU SITE": [""],
            "ESPORTE": ["FUTEBOL AMERICANO"],
            "VESTUARIO": [""],
            "JLR": [""],
            "SERIE": ["FAKING IT"],
            "FILME": ["FAROESTE CABOCLO"],
            "INSETO": [""],
            "MUSICA": [""],
            "LIQUIDO": [""],
            "PCH": ["FIGADO"],
            "NOME MASCULINO": ["FERNANDO"],
            "NOME FEMININO": ["FRANCESCA"],
            "ADJETIVO": ["FORMOSO"],
            "BANDA": ["FRESNO"],
            "PROFISSAO": ["FUZILEIRO"],
            "INSTRUMENTO MUSICAL": ["FLAUTA"],
            "FLV": [""],
            "GENTILICO": [""],
            "CIDADE": [""],
            "GAME": ["FORTNITE"],
            "PERSONAGEM FICTICIO": ["FLASH"],
            "ATOR": ["FABIANA CARLA"],
            "TIME ESPORTIVO": ["FLAMENGO"],
            "OBJETO": ["FORNALHA"],
            "SUPER-HEROI": [""],
            "DESENHO ANIMADO": [""],
            "PALAVRA EM INGLES": [""],
            "SOBREMESA": [""],
            "CANTOR": [""],
            "CANTORA": [""],
            "REMEDIO": [""],
            "COR": ["FERRUGEM"],
            "FRUTA": ["FIGO"],
            "ESPORTISTA": [""],
            "PAIS": ["FILIPINAS"],
            "SOBRENOME": ["FIGUEIRA"],
            "NOME": [""],
            "CAPITAL": [""],
            "MEIO DE TRANSPORTE": ["FOGUETE"],
            "FLOR": ["FLOR DE LIS"],
            "MARCA": ["FORD"],
            "COMIDA": [""],
            "ANIMAL": ["FOCA"],
            "PROGRAMA DE TV": [""]
        },
        "G": {
            "CARRO": ["GOLF"],
            "ALIMENTO": ["GELATINA", "GELEIA"],
            "IDIOMA": [""],
            "DOCE": [""],
            "PDA": ["GASPAZINHO"],
            "CEP": ["GEORGIA"],
            "MSE": ["GORDA"],
            "CELEBRIDADE": ["GLORIA MARIA"],
            "ELETRO ELETRONICO": [""],
            "VERBO": [""],
            "APP OU SITE": [""],
            "ESPORTE": ["GINASTICA"],
            "VESTUARIO": [""],
            "JLR": [""],
            "SERIE": ["GAME OF THRONES"],
            "FILME": ["GAROTAS SELVAGENS"],
            "INSETO": [""],
            "MUSICA": [""],
            "LIQUIDO": [""],
            "PCH": ["GARGANTA"],
            "NOME MASCULINO": ["GUSTAVO"],
            "NOME FEMININO": ["GABRIELLE"],
            "ADJETIVO": ["GENTIL"],
            "BANDA": ["GLORIA"],
            "PROFISSAO": ["GOLEIRO"],
            "INSTRUMENTO MUSICAL": ["GONGO"],
            "FLV": [""],
            "GENTILICO": [""],
            "CIDADE": [""],
            "GAME": ["GTA 5"],
            "PERSONAGEM FICTICIO": ["GROOT"],
            "ATOR": ["GIOVANNA EWBANK"],
            "TIME ESPORTIVO": ["GOIAS"],
            "OBJETO": ["GAIOLA"],
            "SUPER-HEROI": [""],
            "DESENHO ANIMADO": [""],
            "PALAVRA EM INGLES": [""],
            "SOBREMESA": [""],
            "CANTOR": [""],
            "CANTORA": [""],
            "REMEDIO": [""],
            "COR": ["GELO"],
            "FRUTA": ["GRAVIOLA"],
            "ESPORTISTA": [""],
            "PAIS": ["GABAO"],
            "SOBRENOME": ["GARCIA"],
            "NOME": [""],
            "CAPITAL": [""],
            "MEIO DE TRANSPORTE": ["GALEAO"],
            "FLOR": ["GARDENIA"],
            "MARCA": ["GILLETE"],
            "COMIDA": [""],
            "ANIMAL": ["GIRAFA"],
            "PROGRAMA DE TV": [""]
        },
        "H": {
            "CARRO": ["HB20"],
            "ALIMENTO": ["HUMOS"],
            "IDIOMA": [""],
            "DOCE": [""],
            "PDA": ["HE MAN"],
            "CEP": ["HOLAMBRA"],
            "MSE": ["HOSTIL"],
            "CELEBRIDADE": ["HARRY STYLES"],
            "ELETRO ELETRONICO": [""],
            "VERBO": [""],
            "APP OU SITE": [""],
            "ESPORTE": ["HIPISMO"],
            "VESTUARIO": [""],
            "JLR": [""],
            "SERIE": ["HANNIBAL"],
            "FILME": ["HOMEM DE FERRO 3"],
            "INSETO": [""],
            "MUSICA": [""],
            "LIQUIDO": [""],
            "PCH": ["HIPOTALAMO"],
            "NOME MASCULINO": ["HUGO"],
            "NOME FEMININO": ["HELLEN"],
            "ADJETIVO": ["HARMONIOSO"],
            "BANDA": ["HORI"],
            "PROFISSAO": ["HISTORIADOR"],
            "INSTRUMENTO MUSICAL": ["HARPA"],
            "FLV": [""],
            "GENTILICO": [""],
            "CIDADE": [""],
            "GAME": ["HOMEM ARANHA"],
            "PERSONAGEM FICTICIO": ["HOMEM ARANHA"],
            "ATOR": ["HAILEE STEINFIELD"],
            "TIME ESPORTIVO": ["HURACAN"],
            "OBJETO": ["HOLOFOTE"],
            "SUPER-HEROI": [""],
            "DESENHO ANIMADO": [""],
            "PALAVRA EM INGLES": [""],
            "SOBREMESA": [""],
            "CANTOR": [""],
            "CANTORA": [""],
            "REMEDIO": [""],
            "COR": ["HORTELA"],
            "FRUTA": ["Hilocéreo"],
            "ESPORTISTA": [""],
            "PAIS": ["HUNGRIA"],
            "SOBRENOME": ["HABIB"],
            "NOME": [""],
            "CAPITAL": [""],
            "MEIO DE TRANSPORTE": ["HELICOPTERO"],
            "FLOR": ["HIBISCO"],
            "MARCA": ["HAWAN"],
            "COMIDA": [""],
            "ANIMAL": ["HIPOPOTAMO"],
            "PROGRAMA DE TV": [""]
        },
        "I": {
            "CARRO": ["IDEA"],
            "ALIMENTO": ["IOGURTE"],
            "IDIOMA": [""],
            "DOCE": [""],
            "PDA": ["INSPETOR BUGUIGANGA"],
            "CEP": ["INDIANOPOLIS"],
            "MSE": ["INTELIGENTE"],
            "CELEBRIDADE": ["INGRID GUIMARAES"],
            "ELETRO ELETRONICO": [""],
            "VERBO": [""],
            "APP OU SITE": [""],
            "ESPORTE": ["IATISMO"],
            "VESTUARIO": [""],
            "JLR": [""],
            "SERIE": ["IM NOT OKAY WITH THIS"],
            "FILME": ["INTERSTELLAR"],
            "INSETO": [""],
            "MUSICA": [""],
            "LIQUIDO": [""],
            "PCH": ["INTESTINO"],
            "NOME MASCULINO": ["IAGO"],
            "NOME FEMININO": ["ISABELA"],
            "ADJETIVO": ["INTEGRO"],
            "BANDA": ["IRA"],
            "PROFISSAO": ["ILUSTRADOR"],
            "INSTRUMENTO MUSICAL": ["INATA"],
            "FLV": [""],
            "GENTILICO": [""],
            "CIDADE": [""],
            "GAME": ["INDIVISIBLE"],
            "PERSONAGEM FICTICIO": ["IRINEU GRANDE FAMILIA"],
            "ATOR": ["INGRID GUIMARAES"],
            "TIME ESPORTIVO": ["INTERNACIONAL"],
            "OBJETO": ["ISQUEIRO"],
            "SUPER-HEROI": [""],
            "DESENHO ANIMADO": [""],
            "PALAVRA EM INGLES": [""],
            "SOBREMESA": [""],
            "CANTOR": [""],
            "CANTORA": [""],
            "REMEDIO": [""],
            "COR": ["INDIGO"],
            "FRUTA": ["INGA"],
            "ESPORTISTA": [""],
            "PAIS": ["IRLANDA"],
            "SOBRENOME": ["IDALINO"],
            "NOME": [""],
            "CAPITAL": [""],
            "MEIO DE TRANSPORTE": ["IATE"],
            "FLOR": ["IPE"],
            "MARCA": ["INTEL"],
            "COMIDA": [""],
            "ANIMAL": ["IGUANA"],
            "PROGRAMA DE TV": [""]
        },
        "J": {
            "CARRO": ["JEEP"],
            "ALIMENTO": ["JACA"],
            "IDIOMA": [""],
            "DOCE": [""],
            "PDA": ["JUDY JETSON"],
            "CEP": ["JAMAICA"],
            "MSE": ["JOVIAL"],
            "CELEBRIDADE": ["JACK AND JACK"],
            "ELETRO ELETRONICO": [""],
            "VERBO": [""],
            "APP OU SITE": [""],
            "ESPORTE": ["JUDO"],
            "VESTUARIO": [""],
            "JLR": [""],
            "SERIE": ["JESSICA JONES"],
            "FILME": ["JACKASS"],
            "INSETO": [""],
            "MUSICA": [""],
            "LIQUIDO": [""],
            "PCH": ["JOELHO"],
            "NOME MASCULINO": ["JULIO"],
            "NOME FEMININO": ["JOAQUINA"],
            "ADJETIVO": ["JUSTO"],
            "BANDA": ["JOTA QUEST"],
            "PROFISSAO": ["JARDINEIRO"],
            "INSTRUMENTO MUSICAL": ["JINKAI"],
            "FLV": [""],
            "GENTILICO": [""],
            "CIDADE": [""],
            "GAME": ["JUST DANCE"],
            "PERSONAGEM FICTICIO": ["JIRAYA"],
            "ATOR": ["JUSTIN TIMBERLAKE"],
            "TIME ESPORTIVO": ["JUVENTOS"],
            "OBJETO": ["JARRO"],
            "SUPER-HEROI": [""],
            "DESENHO ANIMADO": [""],
            "PALAVRA EM INGLES": [""],
            "SOBREMESA": [""],
            "CANTOR": [""],
            "CANTORA": [""],
            "REMEDIO": [""],
            "COR": ["JADE"],
            "FRUTA": ["JACA"],
            "ESPORTISTA": [""],
            "PAIS": ["JAMAICA"],
            "SOBRENOME": ["JUAREZ"],
            "NOME": [""],
            "CAPITAL": [""],
            "MEIO DE TRANSPORTE": ["JET SKI"],
            "FLOR": ["JASMIN"],
            "MARCA": ["JEEP"],
            "COMIDA": [""],
            "ANIMAL": ["JABUTI"],
            "PROGRAMA DE TV": [""]
        },
        "K": {
            "CARRO": ["KOMBI"],
            "ALIMENTO": ["KIWI"],
            "IDIOMA": [""],
            "DOCE": [""],
            "PDA": ["KABUTU"],
            "CEP": ["KANSAS"],
            "MSE": ["KPOPPER"],
            "CELEBRIDADE": ["KESHA"],
            "ELETRO ELETRONICO": [""],
            "VERBO": [""],
            "APP OU SITE": [""],
            "ESPORTE": ["KARATE"],
            "VESTUARIO": [""],
            "JLR": [""],
            "SERIE": ["KDABRA"],
            "FILME": ["KUNG FU PANDA"],
            "INSETO": [""],
            "MUSICA": [""],
            "LIQUIDO": [""],
            "PCH": ["KALIMBO"],
            "NOME MASCULINO": ["KEVIN"],
            "NOME FEMININO": ["KATIA"],
            "ADJETIVO": ["KPOPPER"],
            "BANDA": ["KLB"],
            "PROFISSAO": ["KARATECA"],
            "INSTRUMENTO MUSICAL": ["KOTO"],
            "FLV": [""],
            "GENTILICO": [""],
            "CIDADE": [""],
            "GAME": ["KINGDOM HEARTS"],
            "PERSONAGEM FICTICIO": ["KEVIN BEN 1O"],
            "ATOR": ["KEFERA"],
            "TIME ESPORTIVO": ["KALAMATA"],
            "OBJETO": ["KINECT"],
            "SUPER-HEROI": [""],
            "DESENHO ANIMADO": [""],
            "PALAVRA EM INGLES": [""],
            "SOBREMESA": [""],
            "CANTOR": [""],
            "CANTORA": [""],
            "REMEDIO": [""],
            "COR": ["KOBI"],
            "FRUTA": ["KIWI"],
            "ESPORTISTA": [""],
            "PAIS": ["KUWAIT"],
            "SOBRENOME": ["KLEIN"],
            "NOME": [""],
            "CAPITAL": [""],
            "MEIO DE TRANSPORTE": ["KITE SURF"],
            "FLOR": ["KAVAKAVA"],
            "MARCA": ["KALUNGA"],
            "COMIDA": [""],
            "ANIMAL": ["KOWARI MAMIFERO"],
            "PROGRAMA DE TV": [""]
        },
        "L": {
            "CARRO": ["LAMBORGHINI"],
            "ALIMENTO": ["LEITE"],
            "IDIOMA": [""],
            "DOCE": [""],
            "PDA": ["LEITAO"],
            "CEP": ["LOS ANGELES"],
            "MSE": ["LINDA"],
            "CELEBRIDADE": ["LIAM PAYNE"],
            "ELETRO ELETRONICO": [""],
            "VERBO": [""],
            "APP OU SITE": [""],
            "ESPORTE": ["LUTA GRECO ROMANA"],
            "VESTUARIO": [""],
            "JLR": [""],
            "SERIE": ["LA CASA DE PAPEL"],
            "FILME": ["LILO E STITCH"],
            "INSETO": [""],
            "MUSICA": [""],
            "LIQUIDO": [""],
            "PCH": ["LARINGE"],
            "NOME MASCULINO": ["LUIZ"],
            "NOME FEMININO": ["LUANA"],
            "ADJETIVO": ["LOUVAVEL"],
            "BANDA": ["LEGIAO URBANA"],
            "PROFISSAO": ["LANTERNINHA"],
            "INSTRUMENTO MUSICAL": ["LIRA"],
            "FLV": [""],
            "GENTILICO": [""],
            "CIDADE": [""],
            "GAME": ["LEAGUE OF LEGENDS"],
            "PERSONAGEM FICTICIO": ["LANCELOT"],
            "ATOR": ["LILY JAMES"],
            "TIME ESPORTIVO": ["LIVERPOOL"],
            "OBJETO": ["LUVAS"],
            "SUPER-HEROI": [""],
            "DESENHO ANIMADO": [""],
            "PALAVRA EM INGLES": [""],
            "SOBREMESA": [""],
            "CANTOR": [""],
            "CANTORA": [""],
            "REMEDIO": [""],
            "COR": ["LARANJA"],
            "FRUTA": ["LIMAO"],
            "ESPORTISTA": [""],
            "PAIS": ["LIBIA"],
            "SOBRENOME": ["LOPES"],
            "NOME": [""],
            "CAPITAL": [""],
            "MEIO DE TRANSPORTE": ["LANCHA"],
            "FLOR": ["LIRIO"],
            "MARCA": ["LACOSTE"],
            "COMIDA": [""],
            "ANIMAL": ["LONTRA"],
            "PROGRAMA DE TV": [""]
        },
        "M": {
            "CARRO": ["MUSTANG"],
            "ALIMENTO": ["MANDIOCA"],
            "IDIOMA": [""],
            "DOCE": [""],
            "PDA": ["MAGALI"],
            "CEP": ["MOCAMBIQUE"],
            "MSE": ["MEIGA"],
            "CELEBRIDADE": ["MADONNA"],
            "ELETRO ELETRONICO": [""],
            "VERBO": [""],
            "APP OU SITE": [""],
            "ESPORTE": ["MUAY-THAI"],
            "VESTUARIO": [""],
            "JLR": [""],
            "SERIE": ["MAD MAN"],
            "FILME": ["MULHER MARAVILHA"],
            "INSETO": [""],
            "MUSICA": [""],
            "LIQUIDO": [""],
            "PCH": ["MAXILAR"],
            "NOME MASCULINO": ["MARCIEL"],
            "NOME FEMININO": ["MARIANA"],
            "ADJETIVO": ["MARIVILHOSA"],
            "BANDA": ["MAMONAS ASSASINAS"],
            "PROFISSAO": ["MAESTRO"],
            "INSTRUMENTO MUSICAL": ["MARIMBA"],
            "FLV": [""],
            "GENTILICO": [""],
            "CIDADE": [""],
            "GAME": ["MAD MAX"],
            "PERSONAGEM FICTICIO": ["MARIO"],
            "ATOR": ["MISHA COLLINS"],
            "TIME ESPORTIVO": ["MILAN"],
            "OBJETO": ["MOCHILA"],
            "SUPER-HEROI": [""],
            "DESENHO ANIMADO": [""],
            "PALAVRA EM INGLES": [""],
            "SOBREMESA": [""],
            "CANTOR": [""],
            "CANTORA": [""],
            "REMEDIO": [""],
            "COR": ["MARROM"],
            "FRUTA": ["MACA"],
            "ESPORTISTA": [""],
            "PAIS": ["MACEDONIA"],
            "SOBRENOME": ["MARTINZ"],
            "NOME": [""],
            "CAPITAL": [""],
            "MEIO DE TRANSPORTE": ["MOTO"],
            "FLOR": ["MAGNOLIA"],
            "MARCA": ["MOTOROLA"],
            "COMIDA": [""],
            "ANIMAL": ["MORCEGO"],
            "PROGRAMA DE TV": [""]
        },
        "N": {
            "CARRO": ["NEXUS"],
            "ALIMENTO": ["NACHOS"],
            "IDIOMA": [""],
            "DOCE": [""],
            "PDA": ["NOTURNO"],
            "CEP": ["NORUEGA"],
            "MSE": ["NOTAVEL"],
            "CELEBRIDADE": ["NALDO BENNY"],
            "ELETRO ELETRONICO": [""],
            "VERBO": [""],
            "APP OU SITE": [""],
            "ESPORTE": ["NATACAO"],
            "VESTUARIO": [""],
            "JLR": [""],
            "SERIE": ["NARCOS"],
            "FILME": ["NANNY MCPHEE"],
            "INSETO": [""],
            "MUSICA": [""],
            "LIQUIDO": [""],
            "PCH": ["NARIZ"],
            "NOME MASCULINO": ["NATAN"],
            "NOME FEMININO": ["NORMA"],
            "ADJETIVO": ["NOTAVEL"],
            "BANDA": ["NXZERO"],
            "PROFISSAO": ["NARRADOR"],
            "INSTRUMENTO MUSICAL": ["NIANCO"],
            "FLV": [""],
            "GENTILICO": [""],
            "CIDADE": [""],
            "GAME": ["NEED FOR SPEED"],
            "PERSONAGEM FICTICIO": ["NARUTO"],
            "ATOR": ["NICETTE BRUNO"],
            "TIME ESPORTIVO": ["NAUTICO"],
            "OBJETO": ["NOVELO"],
            "SUPER-HEROI": [""],
            "DESENHO ANIMADO": [""],
            "PALAVRA EM INGLES": [""],
            "SOBREMESA": [""],
            "CANTOR": [""],
            "CANTORA": [""],
            "REMEDIO": [""],
            "COR": ["NEVE"],
            "FRUTA": ["NESPERA"],
            "ESPORTISTA": [""],
            "PAIS": ["NIGERIA"],
            "SOBRENOME": ["NOVAES"],
            "NOME": [""],
            "CAPITAL": [""],
            "MEIO DE TRANSPORTE": ["NAVE ESPACIAL"],
            "FLOR": ["NARCISO"],
            "MARCA": ["NIKE"],
            "COMIDA": [""],
            "ANIMAL": ["NAJA"],
            "PROGRAMA DE TV": [""]
        },
        "O": {
            "CARRO": ["ONIX"],
            "ALIMENTO": ["OVO"],
            "IDIOMA": [""],
            "DOCE": [""],
            "PDA": ["OLIVIA PALITO"],
            "CEP": ["ORLANDO"],
            "MSE": ["ORDINARIA"],
            "CELEBRIDADE": ["OWEN WILSON"],
            "ELETRO ELETRONICO": [""],
            "VERBO": [""],
            "APP OU SITE": [""],
            "ESPORTE": ["ONDULACAO"],
            "VESTUARIO": [""],
            "JLR": [""],
            "SERIE": ["ONCE UPON A TIME"],
            "FILME": ["O DIARIO DE BRIDGET JONES"],
            "INSETO": [""],
            "MUSICA": [""],
            "LIQUIDO": [""],
            "PCH": ["OMBROS"],
            "NOME MASCULINO": ["OSVALDO"],
            "NOME FEMININO": ["OTAVIA"],
            "ADJETIVO": ["OTIMISTA"],
            "BANDA": ["ONZE 2O"],
            "PROFISSAO": ["OFTALMOLOGISTA"],
            "INSTRUMENTO MUSICAL": ["OBOE"],
            "FLV": [""],
            "GENTILICO": [""],
            "CIDADE": [""],
            "GAME": ["OUTLAST"],
            "PERSONAGEM FICTICIO": ["OCTAVIA BLAKE"],
            "ATOR": ["OSMAR PRADO"],
            "TIME ESPORTIVO": ["OESTE"],
            "OBJETO": ["OCULOS"],
            "SUPER-HEROI": [""],
            "DESENHO ANIMADO": [""],
            "PALAVRA EM INGLES": [""],
            "SOBREMESA": [""],
            "CANTOR": [""],
            "CANTORA": [""],
            "REMEDIO": [""],
            "COR": ["OCRE"],
            "FRUTA": ["OITI EH UMA FRUTA"],
            "ESPORTISTA": [""],
            "PAIS": ["OMA"],
            "SOBRENOME": ["OLIVEIRA"],
            "NOME": [""],
            "CAPITAL": [""],
            "MEIO DE TRANSPORTE": ["ONIBUS"],
            "FLOR": ["ORQUIDEA"],
            "MARCA": ["OUTBACK"],
            "COMIDA": [""],
            "ANIMAL": ["ORNITORRINCO"],
            "PROGRAMA DE TV": [""]
        },
        "P": {
            "CARRO": ["PALIO"],
            "ALIMENTO": ["PATE"],
            "IDIOMA": [""],
            "DOCE": [""],
            "PDA": ["PAPALEGUAS"],
            "CEP": ["PATO BRANCO"],
            "MSE": ["POSITIVA"],
            "CELEBRIDADE": ["PAULO GUSTAVO"],
            "ELETRO ELETRONICO": [""],
            "VERBO": [""],
            "APP OU SITE": [""],
            "ESPORTE": ["PATINACAO"],
            "VESTUARIO": [""],
            "JLR": [""],
            "SERIE": ["PAN AM"],
            "FILME": ["PERCY JACKSON E O LADRAO DE RAIOS"],
            "INSETO": [""],
            "MUSICA": [""],
            "LIQUIDO": [""],
            "PCH": ["PUMAO"],
            "NOME MASCULINO": ["PIETRO"],
            "NOME FEMININO": ["PAMELA"],
            "ADJETIVO": ["PRATICO"],
            "BANDA": ["PATO FU"],
            "PROFISSAO": ["PORTEIRO"],
            "INSTRUMENTO MUSICAL": ["PIANO"],
            "FLV": [""],
            "GENTILICO": [""],
            "CIDADE": [""],
            "GAME": ["PACMAN"],
            "PERSONAGEM FICTICIO": ["PETER PARKER"],
            "ATOR": ["PENELOPE CRUZ"],
            "TIME ESPORTIVO": ["PALMEIRAS"],
            "OBJETO": ["PEDRA"],
            "SUPER-HEROI": [""],
            "DESENHO ANIMADO": [""],
            "PALAVRA EM INGLES": [""],
            "SOBREMESA": [""],
            "CANTOR": [""],
            "CANTORA": [""],
            "REMEDIO": [""],
            "COR": ["PRETO"],
            "FRUTA": ["PERA"],
            "ESPORTISTA": [""],
            "PAIS": ["PANAMA"],
            "SOBRENOME": ["PINTO"],
            "NOME": [""],
            "CAPITAL": [""],
            "MEIO DE TRANSPORTE": ["PLANADOR"],
            "FLOR": ["PAPOULA"],
            "MARCA": ["PANASONIC"],
            "COMIDA": [""],
            "ANIMAL": ["PATO"],
            "PROGRAMA DE TV": [""]
        },
        "Q": {
            "CARRO": ["Q7"],
            "ALIMENTO": ["QUEIJO"],
            "IDIOMA": [""],
            "DOCE": [""],
            "PDA": ["QUINDIM"],
            "CEP": ["QUENIA"],
            "MSE": ["QUERIDA"],
            "CELEBRIDADE": ["QUINN SHEPHARD"],
            "ELETRO ELETRONICO": [""],
            "VERBO": [""],
            "APP OU SITE": [""],
            "ESPORTE": ["QUEIMADA"],
            "VESTUARIO": [""],
            "JLR": [""],
            "SERIE": ["QUANTICO"],
            "FILME": ["QUERIDO JOHN"],
            "INSETO": [""],
            "MUSICA": [""],
            "LIQUIDO": [""],
            "PCH": ["QUEIXO"],
            "NOME MASCULINO": ["QUEMUEL"],
            "NOME FEMININO": ["QUESIA"],
            "ADJETIVO": ["QUERIDO"],
            "BANDA": ["QUEEN"],
            "PROFISSAO": ["QUEIJEIRO"],
            "INSTRUMENTO MUSICAL": ["QUENA"],
            "FLV": [""],
            "GENTILICO": [""],
            "CIDADE": [""],
            "GAME": ["QUAKE 4"],
            "PERSONAGEM FICTICIO": ["QUENTIN LANCE ARROW"],
            "ATOR": ["QUENTIN TARANTINO"],
            "TIME ESPORTIVO": ["QUEIMADENSE"],
            "OBJETO": ["QUADRO"],
            "SUPER-HEROI": [""],
            "DESENHO ANIMADO": [""],
            "PALAVRA EM INGLES": [""],
            "SOBREMESA": [""],
            "CANTOR": [""],
            "CANTORA": [""],
            "REMEDIO": [""],
            "COR": ["QUARTZ"],
            "FRUTA": ["QUINA"],
            "ESPORTISTA": [""],
            "PAIS": ["QATAR"],
            "SOBRENOME": ["QUARESMA"],
            "NOME": [""],
            "CAPITAL": [""],
            "MEIO DE TRANSPORTE": ["QUADRICICULO"],
            "FLOR": ["QUARESMEIRA"],
            "MARCA": ["QUERO"],
            "COMIDA": [""],
            "ANIMAL": ["QUATI"],
            "PROGRAMA DE TV": [""]
        },
        "R": {
            "CARRO": ["RANGER ROVER"],
            "ALIMENTO": ["RÚCULA"],
            "IDIOMA": [""],
            "DOCE": [""],
            "PDA": ["ROCK LEE"],
            "CEP": ["RORAIMA"],
            "MSE": ["RIDICULA"],
            "CELEBRIDADE": ["RIHANNA"],
            "ELETRO ELETRONICO": [""],
            "VERBO": [""],
            "APP OU SITE": [""],
            "ESPORTE": ["RUGBY"],
            "VESTUARIO": [""],
            "JLR": [""],
            "SERIE": ["RAGNAROK"],
            "FILME": ["RESGATE A BAIXO DE ZERO"],
            "INSETO": [""],
            "MUSICA": [""],
            "LIQUIDO": [""],
            "PCH": ["RIM"],
            "NOME MASCULINO": ["RONALDO"],
            "NOME FEMININO": ["RENATA"],
            "ADJETIVO": ["RESPOSAVEL"],
            "BANDA": ["RED HOT CHILI PEPPERS"],
            "PROFISSAO": ["ROTEIRISTA"],
            "INSTRUMENTO MUSICAL": ["REPINQUE"],
            "FLV": [""],
            "GENTILICO": [""],
            "CIDADE": [""],
            "GAME": ["ROCKET LEAGUE"],
            "PERSONAGEM FICTICIO": ["ROCK LEE"],
            "ATOR": ["RIHANNA"],
            "TIME ESPORTIVO": ["REAL MADRID"],
            "OBJETO": ["ROLETA"],
            "SUPER-HEROI": [""],
            "DESENHO ANIMADO": [""],
            "PALAVRA EM INGLES": [""],
            "SOBREMESA": [""],
            "CANTOR": [""],
            "CANTORA": [""],
            "REMEDIO": [""],
            "COR": ["ROSA"],
            "FRUTA": ["ROMA"],
            "ESPORTISTA": [""],
            "PAIS": ["REINO UNIDO"],
            "SOBRENOME": ["RAMALHO"],
            "NOME": [""],
            "CAPITAL": [""],
            "MEIO DE TRANSPORTE": ["RETROESCAVADEIRA"],
            "FLOR": ["ROSA VERMELHA"],
            "MARCA": ["RENAULT"],
            "COMIDA": [""],
            "ANIMAL": ["RATAZANA"],
            "PROGRAMA DE TV": [""]
        },
        "S": {
            "CARRO": ["SANTANA"],
            "ALIMENTO": ["SORVETE"],
            "IDIOMA": [""],
            "DOCE": [""],
            "PDA": ["SCOOBY DOO"],
            "CEP": ["SALVADOR"],
            "MSE": ["SISTEMATICA"],
            "CELEBRIDADE": ["SUSANA VIEIRA"],
            "ELETRO ELETRONICO": [""],
            "VERBO": [""],
            "APP OU SITE": [""],
            "ESPORTE": ["SURF"],
            "VESTUARIO": [""],
            "JLR": [""],
            "SERIE": ["SABRINA A APRENDIZ DE FEITICERA"],
            "FILME": ["SE EU FOSSE VOCE"],
            "INSETO": [""],
            "MUSICA": [""],
            "LIQUIDO": [""],
            "PCH": ["SOVACO"],
            "NOME MASCULINO": ["SANDRO"],
            "NOME FEMININO": ["SAMANTA"],
            "ADJETIVO": ["SABIO"],
            "BANDA": ["SCRACHO"],
            "PROFISSAO": ["SEGUNRAÇA"],
            "INSTRUMENTO MUSICAL": ["SINO"],
            "FLV": [""],
            "GENTILICO": [""],
            "CIDADE": [""],
            "GAME": ["STOPOTS"],
            "PERSONAGEM FICTICIO": ["SASUKE"],
            "ATOR": ["SANDRA BULLECK"],
            "TIME ESPORTIVO": ["SANTOS"],
            "OBJETO": ["SALEIRO"],
            "SUPER-HEROI": [""],
            "DESENHO ANIMADO": [""],
            "PALAVRA EM INGLES": [""],
            "SOBREMESA": [""],
            "CANTOR": [""],
            "CANTORA": [""],
            "REMEDIO": [""],
            "COR": ["SALMAO"],
            "FRUTA": ["SAPUCAIA"],
            "ESPORTISTA": [""],
            "PAIS": ["SURINAME"],
            "SOBRENOME": ["SOUZA"],
            "NOME": [""],
            "CAPITAL": [""],
            "MEIO DE TRANSPORTE": ["SKATE"],
            "FLOR": ["SALVIA"],
            "MARCA": ["SONY"],
            "COMIDA": [""],
            "ANIMAL": ["SERPENTE"],
            "PROGRAMA DE TV": [""]
        },
        "T": {
            "CARRO": ["TUCSON"],
            "ALIMENTO": ["TILAPIA"],
            "IDIOMA": [""],
            "DOCE": [""],
            "PDA": ["TEMPESTADE"],
            "CEP": ["TUNISIA"],
            "MSE": ["TRAIRA"],
            "CELEBRIDADE": ["TESSA"],
            "ELETRO ELETRONICO": [""],
            "VERBO": [""],
            "APP OU SITE": [""],
            "ESPORTE": ["TENIS"],
            "VESTUARIO": [""],
            "JLR": [""],
            "SERIE": ["TEENWOLF"],
            "FILME": ["TA CHOVENDO HAMBURGUER"],
            "INSETO": [""],
            "MUSICA": [""],
            "LIQUIDO": [""],
            "PCH": ["TORNOZELO"],
            "NOME MASCULINO": ["THULIO"],
            "NOME FEMININO": ["TANIA"],
            "ADJETIVO": ["TOLERANTE"],
            "BANDA": ["TITAS"],
            "PROFISSAO": ["TABELIAO"],
            "INSTRUMENTO MUSICAL": ["TRIANGULO"],
            "FLV": [""],
            "GENTILICO": [""],
            "CIDADE": [""],
            "GAME": ["TIBIA"],
            "PERSONAGEM FICTICIO": ["THANOS"],
            "ATOR": ["TESSA THOMPSON"],
            "TIME ESPORTIVO": ["TAGUATINGA"],
            "OBJETO": ["TESOURA"],
            "SUPER-HEROI": [""],
            "DESENHO ANIMADO": [""],
            "PALAVRA EM INGLES": [""],
            "SOBREMESA": [""],
            "CANTOR": [""],
            "CANTORA": [""],
            "REMEDIO": [""],
            "COR": ["TURQUESA"],
            "FRUTA": ["TANGERINA"],
            "ESPORTISTA": [""],
            "PAIS": ["TANZANIA"],
            "SOBRENOME": ["TEIXEIRA"],
            "NOME": [""],
            "CAPITAL": [""],
            "MEIO DE TRANSPORTE": ["TREM BALA"],
            "FLOR": ["TULIPA"],
            "MARCA": ["TOPPER"],
            "COMIDA": [""],
            "ANIMAL": ["TEXUGO"],
            "PROGRAMA DE TV": [""]
        },
        "U": {
            "CARRO": ["UNO FIRE"],
            "ALIMENTO": ["UVA"],
            "IDIOMA": [""],
            "DOCE": [""],
            "PDA": ["UNI"],
            "CEP": ["UTAH"],
            "MSE": ["UTIL"],
            "CELEBRIDADE": ["USHER"],
            "ELETRO ELETRONICO": [""],
            "VERBO": [""],
            "APP OU SITE": [""],
            "ESPORTE": ["ULTRAMARATONA"],
            "VESTUARIO": [""],
            "JLR": [""],
            "SERIE": ["UNDER THE DOME"],
            "FILME": ["UMA PROVA DE AMOR"],
            "INSETO": [""],
            "MUSICA": [""],
            "LIQUIDO": [""],
            "PCH": ["UTERO"],
            "NOME MASCULINO": ["ULISSES"],
            "NOME FEMININO": ["URSULA"],
            "ADJETIVO": ["UNICO"],
            "BANDA": ["ULTRAJE A RIGOR"],
            "PROFISSAO": ["URBANISTA"],
            "INSTRUMENTO MUSICAL": ["UCULELE"],
            "FLV": [""],
            "GENTILICO": [""],
            "CIDADE": [""],
            "GAME": ["UNDER ARMS"],
            "PERSONAGEM FICTICIO": ["ULTRON"],
            "ATOR": ["URIEL DEL TORO"],
            "TIME ESPORTIVO": ["UBERABA"],
            "OBJETO": ["URNA"],
            "SUPER-HEROI": [""],
            "DESENHO ANIMADO": [""],
            "PALAVRA EM INGLES": [""],
            "SOBREMESA": [""],
            "CANTOR": [""],
            "CANTORA": [""],
            "REMEDIO": [""],
            "COR": ["URANO"],
            "FRUTA": ["UVA"],
            "ESPORTISTA": [""],
            "PAIS": ["UGANDA"],
            "SOBRENOME": ["UDISSSON"],
            "NOME": [""],
            "CAPITAL": [""],
            "MEIO DE TRANSPORTE": ["UNICORNIO"],
            "FLOR": ["UNHA DE GATO"],
            "MARCA": ["UMBRO"],
            "COMIDA": [""],
            "ANIMAL": ["URSO"],
            "PROGRAMA DE TV": [""]
        },
        "V": {
            "CARRO": ["VECTRA"],
            "ALIMENTO": ["VATAPA"],
            "IDIOMA": [""],
            "DOCE": [""],
            "PDA": ["VELMA SCOOBY"],
            "CEP": ["VENEZUELA"],
            "MSE": ["VALENTE"],
            "CELEBRIDADE": ["VANESSA DA MATA"],
            "ELETRO ELETRONICO": [""],
            "VERBO": [""],
            "APP OU SITE": [""],
            "ESPORTE": ["VOLEI"],
            "VESTUARIO": [""],
            "JLR": [""],
            "SERIE": ["VAN HELSING"],
            "FILME": ["VALENTE"],
            "INSETO": [""],
            "MUSICA": [""],
            "LIQUIDO": [""],
            "PCH": ["VEIAS"],
            "NOME MASCULINO": ["VINICIUS"],
            "NOME FEMININO": ["VANESSA"],
            "ADJETIVO": ["VERDADEIRO"],
            "BANDA": ["VESGAS MANDARINAS"],
            "PROFISSAO": ["VENDEDOR"],
            "INSTRUMENTO MUSICAL": ["VIOLONCELO"],
            "FLV": [""],
            "GENTILICO": [""],
            "CIDADE": [""],
            "GAME": ["VALORANT"],
            "PERSONAGEM FICTICIO": ["VAMPIRA XMEN"],
            "ATOR": ["VIOLA DAVIS"],
            "TIME ESPORTIVO": ["VASCO"],
            "OBJETO": ["VIBRADOR"],
            "SUPER-HEROI": [""],
            "DESENHO ANIMADO": [""],
            "PALAVRA EM INGLES": [""],
            "SOBREMESA": [""],
            "CANTOR": [""],
            "CANTORA": [""],
            "REMEDIO": [""],
            "COR": ["VIOLETA"],
            "FRUTA": ["VERGAMOTA"],
            "ESPORTISTA": [""],
            "PAIS": ["VATICANO"],
            "SOBRENOME": ["VENANCIO"],
            "NOME": [""],
            "CAPITAL": [""],
            "MEIO DE TRANSPORTE": ["VAN"],
            "FLOR": ["VIOLETA"],
            "MARCA": ["VANS"],
            "COMIDA": [""],
            "ANIMAL": ["VESPA"],
            "PROGRAMA DE TV": [""]
        },
        "W": {
            "CARRO": ["WEEKEND"],
            "ALIMENTO": ["WAFFLE"],
            "IDIOMA": [""],
            "DOCE": [""],
            "PDA": ["WOLVERINE"],
            "CEP": ["WASHINGTON"],
            "MSE": ["WAKANDIANA"],
            "CELEBRIDADE": ["WESLEY SAFADAO"],
            "ELETRO ELETRONICO": [""],
            "VERBO": [""],
            "APP OU SITE": [""],
            "ESPORTE": ["WINDSURF"],
            "VESTUARIO": [""],
            "JLR": [""],
            "SERIE": ["WANDAVISION"],
            "FILME": ["WENDY WU A GAROTA KUNG FU"],
            "INSETO": [""],
            "MUSICA": [""],
            "LIQUIDO": [""],
            "PCH": ["WANO"],
            "NOME MASCULINO": ["WEDSON"],
            "NOME FEMININO": ["WANDA"],
            "ADJETIVO": ["WAKANDIANA"],
            "BANDA": ["WOLFMOTHER"],
            "PROFISSAO": ["WEB DESIGNER"],
            "INSTRUMENTO MUSICAL": ["WEBOS"],
            "FLV": [""],
            "GENTILICO": [""],
            "CIDADE": [""],
            "GAME": ["WATCH DOGS"],
            "PERSONAGEM FICTICIO": ["WANDA"],
            "ATOR": ["WESLEY SNIPES"],
            "TIME ESPORTIVO": ["WENCESLAUENSE"],
            "OBJETO": ["WALKIE TALKIE"],
            "SUPER-HEROI": [""],
            "DESENHO ANIMADO": [""],
            "PALAVRA EM INGLES": [""],
            "SOBREMESA": [""],
            "CANTOR": [""],
            "CANTORA": [""],
            "REMEDIO": [""],
            "COR": ["WISTERIA"],
            "FRUTA": ["WAMPI"],
            "ESPORTISTA": [""],
            "PAIS": ["WALLIS"],
            "SOBRENOME": ["WALDORF"],
            "NOME": [""],
            "CAPITAL": [""],
            "MEIO DE TRANSPORTE": ["WIND SURF"],
            "FLOR": ["WALLFLOWER"],
            "MARCA": ["WARNER"],
            "COMIDA": [""],
            "ANIMAL": ["WALLABY MARSUPIAL"],
            "PROGRAMA DE TV": [""]
        },
        "X": {
            "CARRO": ["X60"],
            "ALIMENTO": ["XYNOTYRO EH UM QUEIJO"],
            "IDIOMA": [""],
            "DOCE": [""],
            "PDA": ["XUXU MANDA CHUVA"],
            "CEP": ["XANGAI"],
            "MSE": ["XERETA"],
            "CELEBRIDADE": ["XUXA"],
            "ELETRO ELETRONICO": [""],
            "VERBO": [""],
            "APP OU SITE": [""],
            "ESPORTE": ["XADREZ"],
            "VESTUARIO": [""],
            "JLR": [""],
            "SERIE": ["XENA A PRINCESA GUERREIRA"],
            "FILME": ["X MEN REVOLUTION"],
            "INSETO": [""],
            "MUSICA": [""],
            "LIQUIDO": [""],
            "PCH": ["XONODO"],
            "NOME MASCULINO": ["XANDE"],
            "NOME FEMININO": ["XENA"],
            "ADJETIVO": ["XAVECADOR"],
            "BANDA": ["XANDRIA"],
            "PROFISSAO": ["XERIFE"],
            "INSTRUMENTO MUSICAL": ["XILOFONE"],
            "FLV": [""],
            "GENTILICO": [""],
            "CIDADE": [""],
            "GAME": ["X MEN BATLE OF ATON"],
            "PERSONAGEM FICTICIO": ["X23 XMEN"],
            "ATOR": ["XANDER BERKELEY"],
            "TIME ESPORTIVO": ["XV DE NOVEMBRO"],
            "OBJETO": ["XICARA"],
            "SUPER-HEROI": [""],
            "DESENHO ANIMADO": [""],
            "PALAVRA EM INGLES": [""],
            "SOBREMESA": [""],
            "CANTOR": [""],
            "CANTORA": [""],
            "REMEDIO": [""],
            "COR": ["XANADU"],
            "FRUTA": ["XIXA"],
            "ESPORTISTA": [""],
            "PAIS": ["XEXENIA"],
            "SOBRENOME": ["XAVIER"],
            "NOME": [""],
            "CAPITAL": [""],
            "MEIO DE TRANSPORTE": ["XEBEC"],
            "FLOR": ["XANANA"],
            "MARCA": ["XBOX"],
            "COMIDA": [""],
            "ANIMAL": ["XARU BAGRE"],
            "PROGRAMA DE TV": [""]
        },
        "Y": {
            "CARRO": ["YARIS TOYOTA"],
            "ALIMENTO": ["YAKISOBA"],
            "IDIOMA": [""],
            "DOCE": [""],
            "PDA": ["YAMATO"],
            "CEP": ["YOKOHAMA"],
            "MSE": ["YOUNG"],
            "CELEBRIDADE": ["YASMIN SANTOS"],
            "ELETRO ELETRONICO": [""],
            "VERBO": [""],
            "APP OU SITE": [""],
            "ESPORTE": ["YOGA"],
            "VESTUARIO": [""],
            "JLR": [""],
            "SERIE": ["Y THE LAST MAN"],
            "FILME": ["YAKUZA APOCALIPSE"],
            "INSETO": [""],
            "MUSICA": [""],
            "LIQUIDO": [""],
            "PCH": ["YORCA"],
            "NOME MASCULINO": ["YURI"],
            "NOME FEMININO": ["YARA"],
            "ADJETIVO": ["YOUNG"],
            "BANDA": ["YELLOWCARD"],
            "PROFISSAO": ["YOUTUBER"],
            "INSTRUMENTO MUSICAL": ["YNARA"],
            "FLV": [""],
            "GENTILICO": [""],
            "CIDADE": [""],
            "GAME": ["YAKUZA 6"],
            "PERSONAGEM FICTICIO": ["YONDU GUARDIOES"],
            "ATOR": ["YUNA ITO"],
            "TIME ESPORTIVO": ["YANKES"],
            "OBJETO": ["YO YO"],
            "SUPER-HEROI": [""],
            "DESENHO ANIMADO": [""],
            "PALAVRA EM INGLES": [""],
            "SOBREMESA": [""],
            "CANTOR": [""],
            "CANTORA": [""],
            "REMEDIO": [""],
            "COR": ["YALE BLUE"],
            "FRUTA": ["YUZU"],
            "ESPORTISTA": [""],
            "PAIS": ["YEMEN"],
            "SOBRENOME": ["YORK"],
            "NOME": [""],
            "CAPITAL": [""],
            "MEIO DE TRANSPORTE": ["YAK"],
            "FLOR": ["YIANTIA"],
            "MARCA": ["YAKUTI"],
            "COMIDA": [""],
            "ANIMAL": ["YAK BOI SELVAGEM"],
            "PROGRAMA DE TV": [""]
        },
        "Z": {
            "CARRO": ["ZAFIRA"],
            "ALIMENTO": ["ZITRONE EH UM LIMAO)"],
            "IDIOMA": [""],
            "DOCE": [""],
            "PDA": ["ZANGADO"],
            "CEP": ["ZIMBABUE"],
            "MSE": ["ZOMBETERA"],
            "CELEBRIDADE": ["ZEZE DI CAMARGO"],
            "ELETRO ELETRONICO": [""],
            "VERBO": [""],
            "APP OU SITE": [""],
            "ESPORTE": ["ZUMBA"],
            "VESTUARIO": [""],
            "JLR": [""],
            "SERIE": ["Z NATION"],
            "FILME": ["ZORRO"],
            "INSETO": [""],
            "MUSICA": [""],
            "LIQUIDO": [""],
            "PCH": ["ZIGOMATICO MAIOR"],
            "NOME MASCULINO": ["ZURIEL"],
            "NOME FEMININO": ["ZOE"],
            "ADJETIVO": ["ZELOSO"],
            "BANDA": ["ZOMBOY"],
            "PROFISSAO": ["ZELADOR"],
            "INSTRUMENTO MUSICAL": ["ZABUMBA"],
            "FLV": [""],
            "GENTILICO": [""],
            "CIDADE": [""],
            "GAME": ["ZELDA"],
            "PERSONAGEM FICTICIO": ["ZECA URUBU"],
            "ATOR": ["ZAC EFFRON"],
            "TIME ESPORTIVO": ["ZUMBI"],
            "OBJETO": ["ZIPER"],
            "SUPER-HEROI": [""],
            "DESENHO ANIMADO": [""],
            "PALAVRA EM INGLES": [""],
            "SOBREMESA": [""],
            "CANTOR": [""],
            "CANTORA": [""],
            "REMEDIO": [""],
            "COR": ["ZAFFRE"],
            "FRUTA": ["ZITRONE EH UM LIMAO"],
            "ESPORTISTA": [""],
            "PAIS": ["ZIMBABUE"],
            "SOBRENOME": ["ZAMBONETTI"],
            "NOME": [""],
            "CAPITAL": [""],
            "MEIO DE TRANSPORTE": ["ZAMBUCO"],
            "FLOR": ["ZAMIOCUCAS"],
            "MARCA": ["ZARA"],
            "COMIDA": [""],
            "ANIMAL": ["ZEBRA"],
            "PROGRAMA DE TV": [""]
        }
    }
    let letter = document.getElementById("letter")
                        .getElementsByTagName("span")[0]
                        .innerText
    let fields = document.getElementsByClassName("content")[0]
                        .getElementsByTagName("div")[0]
                        .getElementsByTagName("div")[0]
                        .getElementsByTagName("label")

    for (let el = 0 ; el < fields.length ; el++)
        if (typeof fields[el] === 'object' && fields[el] !== null){
            let theme = fields[el].getElementsByTagName("span")[0].innerText.replace('"','').normalize("NFD").replace(/[\u0300-\u036f]/g, "")

            fields[el].getElementsByTagName("input")[0].onfocus = () => {
                setTimeout(() => {
                    if (data[letter][theme] !== undefined)
                        fields[el].getElementsByTagName("input")[0].value = data[letter][theme]
                }, 1)
            }
        }
}
